name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ github.workspace }}/TeX-files/main.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ${{ github.workspace }}/TeX-files/fonts/*.ttf
            ${{ github.workspace }}/TeX-files/fonts/*.otf
          working_directory: ${{ github.workspace }}/TeX-files/
          work_in_root_file_dir: true
      - name: Check pdf file
        run: |
          file ${{ github.workspace }}/TeX-files/main.pdf | grep -q ' PDF '
      - name: Upload file to repository
        run: |
          git config --global user.name "filippomazzoli"
          git config --global user.email "filippomazzoli@me.com"
          git add ${{ github.workspace }}/TeX-files/main.pdf
          git commit -m "commit message"
          git push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
