name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ github.workspace }}/TeX-files/main.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ${{ github.workspace }}/TeX-files/fonts/*.ttf
            ${{ github.workspace }}/TeX-files/fonts/*.otf
          working_directory: ${{ github.workspace }}/TeX-files/
          work_in_root_file_dir: true
          
  push_pdf:
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Check pdf file
        run: |
          file ${{ github.workspace }}/TeX-files/main.pdf | grep -q ' PDF '
      - name: Upload pdf. file to repository
        run: |
          git config --global user.name "filippomazzoli"
          git config --global user.email "filippomazzoli@me.com"
          git add ${{ github.workspace }}/TeX-files/main.pdf
          git commit -m "commit message"
          git pull
          git push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        
  push_to_webpage:
    needs: push_pdf
    runs-on: ubuntu-latest
    steps:
      - name: Pushes bibliography file to my academic webpage
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'TeX-files/papers.bib'
          destination_repo: 'filippomazzoli/filippomazzoli.github.io'
          destination_folder: '_bibliography'
          destination_branch: master
          user_email: 'filippomazzoli@me.com'
          user_name: 'filippomazzoli'
      - name: Pushes updated CV file to my academic webpage
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'TeX-files/main.pdf'
          destination_repo: 'filippomazzoli/filippomazzoli.github.io'
          destination_folder: 'assets/pdf'
          destination_branch: master
          user_email: 'filippomazzoli@me.com'
          user_name: 'filippomazzoli'
