name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Pushes papers.bib file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.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 }}
        with:
          source_file: '${{ github.workspace }}/TeX-files/papers.bib'
          destination_repo: 'filippomazzoli/filippomazzoli.github.io'
          destination_folder: '/_bibliography'
          user_email: 'filippomazzoli@me.com'
          user_name: 'filippomazzoli'
          commit_message: 'A custom message for the commit'
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ github.workspace }}/TeX-files/main.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ${{ github.workspace }}/TeX-files/fonts/CormorantGaramond-Regular.ttf
            ${{ github.workspace }}/TeX-files/fonts/fontawesome-free-5.15.4-web.zip
            ${{ github.workspace }}/TeX-files/fonts/academicons-1.9.4.zip
          working_directory: ${{ github.workspace }}/TeX-files/
          work_in_root_file_dir: true
      - name: Check pdf file
        run: |
          file ${{ github.workspace }}/TeX-files/main.pdf | grep -q ' PDF '

      - name: Upload file to repository
        run: |
          git config --global user.name "filippomazzoli"
          git config --global user.email "filippomazzoli@me.com"
          git add ${{ github.workspace }}/TeX-files/main.pdf
          git commit -m "commit message"
          git push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
