name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ github.workspace }}/TeX-files/main.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ${{ github.workspace }}/TeX-files/fonts/CormorantGaramond-Regular.ttf
            ${{ github.workspace }}/TeX-files/fonts/fontawesome-free-5.15.4-web.zip
          working_directory: ${{ github.workspace }}/TeX-files/
          work_in_root_file_dir: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ${{ github.workspace }}/CV.pdf
