name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ github.workspace }}/TeX-files/main.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ${{ github.workspace }}/TeX-files/fonts/CormorantGaramond-Regular.ttf
            ${{ github.workspace }}/TeX-files/fonts/fontawesome-free-5.15.4-web.zip
            ${{ github.workspace }}/TeX-files/fonts/academicons-1.9.4.zip
          working_directory: ${{ github.workspace }}/TeX-files/
          work_in_root_file_dir: true
      - name: Check pdf file
        run: |
          file ${{ github.workspace }}/TeX-files/main.pdf | grep -q ' PDF '

      - name: Upload file to repository
        run: |
          git config --global user.name "your_username"
          git config --global user.email "your_email"
          git add report.pdf
          git commit -m "commit message"
          git push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
