name: 'Update webpage'

on:
  push:
    branches:
      - main

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "I am Workflow of Parent REPO"
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: filippomazzoli
          repo: filippomazzoli.github.io
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: updates-from-CV.yml
          ref: master
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
